#! /bin/sh


echo ---Ce tester ne gere pas: EXIT, RETURN VALUES, SIGNALS, EXPORT  ----\n\n

echo ---------- Simple Command and Global -----------\n
/bin/ls
          
'           '
""
       ""

#echo:
echo ---------- ECHO -----------\n
echo bonjour
echo bonjour les gens
echo -n bonjour les gens
echo -nnnnnnnnnnnnnn bonjour les gens
echo -n-n-n-n-n bonjour 
echo -n -n -n bonjour
echo -n bonjour -n
echo -nnnnnnnnm bonjour
echo “” “” “” bonjour


echo ---------- DOUBLE QUOTES -----------\n
